services:
  cleanarchmvc.webui:
    container_name: app-web
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - "ConnectionStrings:DefaultConnection=Server=sqlserver;Database=cleanArchDb;User Id=sa;Password=2Secure*Password2;Encrypt=False;Trust Server Certificate=True"
    ports:
      - "5000:8080"
    networks: 
      - clean-archtecture-network
    depends_on:
      - sqlserver
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    

  sqlserver:
    container_name: sqlserver
    restart: always
    environment:
      SA_PASSWORD: "2Secure*Password2"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"    
    ports:
      - "1433:1433"
    networks: 
      - clean-archtecture-network
    volumes:
      - sqlserver-data:/var/opt/mssql