### Redes
networks:
  clean-archtecture-network:
    name: clean-archtecture-network
    driver: bridge   
### Volumes
# volumes:
#       sqlserver-data:

### Services
services:
  cleanarchmvc.webui:
    image: ${DOCKER_REGISTRY-}cleanarchmvcwebui
    build:
      context: .
      dockerfile: CleanArchMvc.WebUI/Dockerfile

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
